### ISSUE TITLE
Why use F12 instead of F4

### ISSUE THREAD

**Issue by aliokan** [DoclerLabs/hexDevelop#18]
In HaxeDevelop, Goto Declaration shortcut is F4.

**Comment by chipshort** [comment]
I had some problems when I tried to use F4 in Haxe files (as it was already used for Goto Declaration), so I changed it to F12. However, when I just tested it, it seemed to work fine.
Do you think we should change to F4?

**Comment by aliokan** [comment]
It makes sense. Just an habit to take :)

**Comment by Neverbirth** [comment]
The problem is there is a plugin checking for the current focused part of code, and depending of what you currently have the F4 is disabled or enabled, and it's not as extensible as desired at the moment. If you want to get this working ping me and we can take a look into this together.
