### ISSUE TITLE
Yeoman plugin fails on fresh install

### ISSUE THREAD

**Issue by Neverbirth** [DoclerLabs/hexDevelop#35]
Afer a clean install, and opening hexDevelop.fdz, on FD boot, the Yeoman plugin complained about a missing cmd file, and then we get an error trying to load the plugin, I don't know if the missing cmd is normal (guess it should also be deployed with the fdz?). Anyway, missing the cmd shouldn't make the plugin to fail loading.

**Comment by chipshort** [comment]
If this is what I think, it should be fixed in #31, but I will check again. It also removed the missing cmd message box and replaced it with a message in the output box.
I should probably release an update.

**Comment by Neverbirth** [comment]
Yeah, by looking at the fdz date it looks to be indeed and old one. Would be good to get an up to date one.
